baseURL = 'https://blog.vran29.fr.to/'
languageCode = 'en-us'
title = 'Vran29'
theme = "paper"
enableRobotsTXT = true

[params]
  avatar = 'franvuc@gmail.com'
  name = 'Vran29'
  bio = 'Author'
  github = 'Vran29'
