baseURL = 'https://blog.eason.fr.to/'
languageCode = 'en-us'
title = 'Eason Li'
theme = "paper"

[params]
  avatar = 'lyu63651@gmail.com'
  name = 'Eason Li'
  bio = 'Full Time Linux Nerd'
  twitter = '404'
  github = 'eli32-vlc'
  rss = true
