baseURL = 'https://blog.eason.fr.to/'
languageCode = 'en-us'
title = 'Eason Li'
theme = "paper"
enableRobotsTXT = true

[params]
  avatar = 'lyu63651@gmail.com'
  name = 'Eason Li'
  bio = 'Writer'
  twitter = '404'
  github = 'eli32-vlc'
